[package]
name = "gbfc"
version = "0.1.0"
edition = "2021"
description = "GBFC — General BrainFuck Compiler (AOT + JIT, direct machine code generation)"
license = "MIT"

[lib]
name = "gbfc"
path = "src/lib.rs"

[[bin]]
name = "gbfc"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
